devices:
  - name: "Valve 1"
    ip: 192.168.0.25
    device_id: 1
    pin: 14
    cycle_sec: 10
    duration_ms: 2000
    plants:
      - id: 0
        name: "Plant 1"
  - name: "Valve 2"
    ip: 192.168.0.25
    device_id: 2
    pin: 15
    cycle_sec: 13
    duration_ms: 1000
    plants:
      - id: 1
        name: "Plant 2"
        
pump: 
  pin: 17
  ip: 192.168.0.25
  status: false

tick: 2000
