devices:
  - name: "Valve 1"
    ip: 192.168.0.25
    pin: 14
    cycle_sec: 10
    duration_ms: 2000
    plants:
      - id: 1
        name: "Plant 1"
  - name: "Valve 2"
    ip: 192.168.0.25
    pin: 15
    cycle_sec: 13
    duration_ms: 1000
    plants:
      - id: 2
        name: "Plant 2"
        
pump: 17

tick: 2000
