devices:
  - name: "Valve 1"
    pin: 14
    cycle_sec: 2
    duration_ms: 1000
    plants:
      - id: 1
        name: "Plant 1"
  - name: "Valve 2"
    pin: 15
    cycle_sec: 10
    duration_ms: 8000
    plants:
      - id: 2
        name: "Plant 2"
        
pump: 17

tick: 250
